blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://swiftpackageindex.com/adamtheturtle/FastList/documentation/fastlist
    about: API reference and guides on the Swift Package Index.
